name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          git-user: $USERNAME
          git-password: ${{ secrets.TOKEN }}
          deployment-branch: gh-pages