name: CI
on: 
  push: 
    branches: main

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Build Docusaurus website
        run: |
          cd blog
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: blog/build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}